aquavm_pool_size = 2
tcp_port = 7_771
websocket_port = 9_991
http_port = 18_080
tokio_metrics_enabled = true
metrics_enabled = true
metrics_timer_resolution = "1 minute"

[system_services]
enable = [ "aqua-ipfs", "decider" ]

  [system_services.decider]
  decider_period_sec = 10
  worker_ipfs_multiaddr = "/dns4/ipfs/tcp/5001"
  network_api_endpoint = "http://chain-rpc:8545"
  matcher_address = "0x3Aa5ebB10DC797CAC828524e59A333d0A371443c"
  wallet_key = "0x480e0be8dac777b6a75dbd8b8a4d46f1214d6ee8736f2b927c8b9b18684e5971"
  start_block = "earliest"
  network_id = 31_337

  [system_services.aqua_ipfs]
  external_api_multiaddr = "/ip4/127.0.0.1/tcp/5001"
  local_api_multiaddr = "/dns4/ipfs/tcp/5001"
  ipfs_binary_path = "/usr/bin/ipfs"

[effectors.ipfs]
wasm_cid = "bafkreicrfikfredxsxi2ikyh55eg43kgzgbgakskhdpse3pp4kcxkaq3yu"

  [effectors.ipfs.allowed_binaries]
  ipfs = "/usr/bin/ipfs"

[chain_config]
http_endpoint = "http://chain-rpc:8545"
core_contract_address = "0x0B306BF915C4d645ff596e518fAf3F9669b97016"
cc_contract_address = "0xc6e7DF5E7b4f2A278906862b61205850344D4e7d"
market_contract_address = "0x3Aa5ebB10DC797CAC828524e59A333d0A371443c"
network_id = 31_337
wallet_key = "0x480e0be8dac777b6a75dbd8b8a4d46f1214d6ee8736f2b927c8b9b18684e5971"
default_priority_fee = 0
